FROM golang:1.5.1-onbuild
#FROM gliderlabs/alpine
MAINTAINER Matt Fellows <matt.fellows@onegeek.com.au>

# For the lazy, run the gox command locally
# uncomment this

# ADD microgo microgo
# ENV PORT 80
# EXPOSE 80
# ENTRYPOINT ["/microgo"]

# For the build server - longer but automated
ENV PORT 80
EXPOSE 80
